Lozhkin_LB3/Models/ErrorViewModel.cs
using System;

namespace Lozhkin_LB3.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Lozhkin_LB3/Models/ProductModel.cs
using System.ComponentModel;

namespace Lozhkin_LB3.Models
{
    public class ProductModel
    {
        [DisplayName("Идентификатор")]
        public int Id { get; set; }

        [DisplayName("Название")]
        public string Name { get; set; }

        [DisplayName("Цена")]
        public string Price { get; set; }

        [DisplayName("Описание")]
        public string Description { get; set; }
    }
}

Lozhkin_LB3/Models/StaticDB.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lozhkin_LB3.Models
{
    public static class StaticDB
    {
        public static List<ProductModel> Products { get; set; } = new List<ProductModel>()
        {
            new ProductModel()
            {
                Id = 1,
                Description = "Мяско коровы",
                Name = "Мясо",
                Price = "200 RUB"
            },
                new ProductModel()
            {
                Id = 2,
                Description = "Мяско курицы",
                Name = "Курица",
                Price = "13 RUB"
            },
                new ProductModel()
            {
                Id = 3,
                Description = "Мяско рыбы",
                Name = "Рыбы",
                Price = "45 RUB"
            },
                new ProductModel()
            {
                Id = 4,
                Description = "Пиво Лидское",
                Name = "Вода",
                Price = "35 RUB"
            },
                new ProductModel()
            {
                Id = 5,
                Description = "Мяско Барана",
                Name = "Мясо",
                Price = "95 RUB"
            },
                new ProductModel()
            {
                Id = 6,
                Description = "Вода Бонаква",
                Name = "Вода",
                Price = "25 RUB"
            }
        };
    }
}

Lozhkin_LB3/Controllers/CustomersController.cs
using Lozhkin_LB3.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace Lozhkin_LB3.Controllers
{
    public class CustomersController : Controller
    {
        public IActionResult Add(int productId)
        {
            return View(StaticDB.Products.FirstOrDefault(x=>x.Id == productId));
        }
    }
}

Lozhkin_LB3/Controllers/HomeController.cs
using Lozhkin_LB3.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Lozhkin_LB3.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Lozhkin_LB3/Controllers/ProductsController.cs
using Lozhkin_LB3.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace Lozhkin_LB3.Controllers
{
    public class ProductsController : Controller
    {
        public IActionResult List()
        {
            return View(StaticDB.Products);
        }

        public IActionResult Details(int id)
        {
            return View(StaticDB.Products.FirstOrDefault(x=>x.Id == id));
        }
    }
}

Lozhkin_LB3/Views/Customers/Add.cshtml
@model Lozhkin_LB3.Models.ProductModel

@{
    ViewData["Title"] = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Add</h1>
<div>
    <h4>Продукт</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    <h1>Спасибо за покупку!</h1>
    <a asp-action="List" asp-controller="Products">Вернутся к списку</a>
</div>

Lozhkin_LB3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Lozhkin_LB3/Views/Products/Details.cshtml
@model Lozhkin_LB3.Models.ProductModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Продукт</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="List">Вернутся к списку</a>
</div>

Lozhkin_LB3/Views/Products/List.cshtml
@model IEnumerable<Lozhkin_LB3.Models.ProductModel>

@{
    ViewData["Title"] = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>List</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { Id = item.Id })
                @Html.ActionLink("Add To Cart", "Add", "Customers", new { productId = item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

Lozhkin_LB3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lozhkin_LB3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lozhkin_LB3</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Lozhkin_LB3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>